### ISSUE TITLE
Error in examples/node/main.ts: Cannot find module '@blyss/sdk/node'

### ISSUE THREAD

**Issue by weijiekoh** [blyssprivacy/sdk#14]
Hi,

I tried to run the Node example at `sdk/examples/node` but got this error.

I'm on git commit `aea24b915606bbba12fe80a9c99ee141b01f3eb2` and I'm running Node v18.14.0.

```
$ npx ts-node main.ts
Error: Cannot find module '@blyss/sdk/node'
Require stack:
- /home/user/blyss/sdk/examples/node/main.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/user/blyss/sdk/examples/node/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/user/blyss/sdk/examples/node/main.ts:2:15)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module.m._compile (/home/user/blyss/sdk/examples/node/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Object.require.extensions.<computed> [as .ts] (/home/user/blyss/sdk/examples/node/node_modules/ts-node/src/index.ts:1621:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/user/blyss/sdk/examples/node/main.ts' ]
}
```

**Comment by menonsamir** [comment]
Should be fixed now - thanks for letting me know!
