### ISSUE TITLE
Can't run local examples

### ISSUE THREAD

**Issue by osintalex** [blyssprivacy/sdk#34]
I'm probably missing something quite obvious but getting errors on a fresh checkout after running what the `README.md` says for a local example.

Error:

```
❯ npx ts-node main.ts
webpack:///./data/bloom.ts:70
}
^
jg [Error]: Bad Request
    at webpack:///./client/api.ts:89:11
    at Generator.next (<anonymous>)
    at E (webpack:///./data/bloom.ts:70:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400,
  path: 'http://localhost:8008/setup',
  body: 'Can not decode body',
  msg: 'Bad Request'
}
```

Server logs:

```
Using 4 threads
Listening on 8008
kv_pairs: []
kv_pairs: []
```

Wonder if I missed a stage initializing key pairs somehow?

These are commands I ran:

```shell
cd lib/server
cargo run --release
cd examples/node-local
nvm use --lts
npm i
npx ts-node main.ts
```

**Comment by jayavanth** [comment]
use the tag 0.1.9
